steps:

# build the project
- name: 'mreichelt/android:31'
  id: build
  args: [ "./gradlew", "assembleDebug", "lintDebug", "testDebugUnitTest", "ktlintCheck" ]
  env:
    - 'TERM=dumb'
    - 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dkotlin.incremental=false"'
    - 'BRANCH_NAME=$BRANCH_NAME'

# save APK
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-q', 'cp', '-r', 'app/build/outputs/apk', 'gs://watchlater-build-artifacts/$BRANCH_NAME-$BUILD_ID/']
  waitFor: ['build']

timeout: 1800s
